import base64
import json


def decrypt_base64_json(encoded_data):
    # 解码 Base64 编码的数据
    decoded_data = base64.b64decode(encoded_data)
    # 将解码后的数据转换为字符串
    decoded_string = decoded_data.decode('utf-8')
    # 解析 JSON 数据
    decoded_json_data = json.loads(decoded_string)

    return decoded_json_data


# json_str = {
#     "requestId": 1716515688436,
#     "businessSystemCode": "HAIDING_SYS",
#     "interfaceCode": "BILL.PUSH",
#     "data": "W3siYmlsbE5vIjogIlhTMjAyNDAyMjcwMDM5ODIiLCAiYmlsbERhdGUiOiAiMjAyNC0wMi0yNyIsICJ0b3RhbEFtb3VudCI6IDE0MjUuOSwgImJ1eWVyTmFtZSI6ICJcdTUzNTwcdTViODFcdTVlMDJcdTkwOTVcdTViODFcdTUzM2FcdTg4YjJcdTVlOTlcdTk1NDdcdTY1YjBcdTY1YjBcdTVjMGZcdTViNjYiLCAiYnV5ZXJDb2RlIjogIjAzMDUwMTEiLCAic2VsbGVyVGF4cGF5ZXJJZCI6ICI5MTQ1MDEwME1BNU5DV1E1NkEiLCAic2VsbGVyTmFtZSI6ICJcdTUzNTwcdTViODFcdTVhMDFcdTgwMDBcdTk2YzZcdTkxYzdcdTk2YzZcdTkxNGRcdTRmOWJcdTVlOTRcdTk0ZmVcdTdiYTFcdTc0MDZcdTY3MDlcdTk2NTBcdTUxNmNcdTUzZjgiLCAiaW5jbHVkZVRheEFsYWciOiAiMSIsICJwdXNoTWF0Y2hSdWxlcyI6ICIzIiwgInRleHRGaWVsZDEiOiAiU1DyMDI0MDIwMTM1MjciLCAiYmlsbERldGFpbCI6IFt7ImFtb3VudCI6IDg7My4wLCAicXVhbnRpdHkiOiAyOTEuMCwgImRldGFpbElkIjogIlhTMjAyNDAyMjcwMDM5ODIiLCAiZ29vZHNCb2RlIjogIldZV0wtMDAxMDg3IiwgImxpbmVQcm9wZXJ0eSI6ICIyIiwgInByaWNlIjogMy4wLCAidGF4UmF0ZSI6IDAuMTN9LCB7ImFtb3VudCI6IDU1Mi45LCAicXVhbnTpdHkiOiAyOTEuMCwgImRldGFpbElkIjogIlhTMjAyNDAyMjcwMDM5ODIiLCAiZ29vZHNCb2RlIjogIldZV0wtMDEwNzAwMDMiLCAibGluZVByb3BlcnR5IjogIjIiLCAicHJpY2UiOiAxLjksICJ0YXhSYXRlIjogMC4xM31dfV0="
# }

# encrypted_data = str(json_str["data"])
# print(encrypted_data)
encrypted_data ="W3siYmlsbE5vIjogIlhTMjAyNDAyMjgwMDA5MjkiLCAiYmlsbERhdGUiOiAiMjAyNC0wMi0yOCIsICJ0b3RhbEFtb3VudCI6IDI0MC4wLCAiYnV5ZXJOYW1lIjogIlx1OWE2Y1x1NWM3MVx1NTNiZlx1NzY3ZVx1OWY5OVx1NmVlOVx1OTU0N1x1NTIxZFx1N2VhN1x1NGUyZFx1NWI2NiIsICJidXllckNvZGUiOiAiMTYwMjAwMSIsICJzZWxsZXJUYXhwYXllcklkIjogIjkxNDUwMTAwTUE1TkNXUTU2QSIsICJzZWxsZXJOYW1lIjogIlx1NTM1N1x1NWI4MVx1NWEwMVx1ODAwMFx1OTZjNlx1OTFjN1x1OTZjNlx1OTE0ZFx1NGY5Ylx1NWU5NFx1OTRmZVx1N2JhMVx1NzQwNlx1NjcwOVx1OTY1MFx1NTE2Y1x1NTNmOCIsICJpbmNsdWRlVGF4RmxhZyI6ICIxIiwgInB1c2hNYXRjaFJ1bGVzIjogIjMiLCAidGV4dEZpZWxkMSI6ICJMVDIwMjQwMjAxMzcyNyIsICJiaWxsRGV0YWlsIjogW3siYW1vdW50IjogMjQwLjAsICJxdWFudGl0eSI6IDIuMCwgImRldGFpbElkIjogIlhTMjAyNDAyMjgwMDA5MjkiLCAiZ29vZHNDb2RlIjogIldZV0wtMDIwMTAxMzMiLCAibGluZVByb3BlcnR5IjogIjIiLCAicHJpY2UiOiAxMjAuMCwgInRheFJhdGUiOiAwLjA5fV19XQ=="
print(type(encrypted_data))
# 示例用法
decrypted_data = decrypt_base64_json(encrypted_data)
print(json.dumps(decrypted_data, ensure_ascii=False, indent=2))
